### PR TITLE
Release of tested mosdepth app

### PR DESCRIPTION
**Pull request by jethror1**
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_mosdepth/3)

### CODE REVIEW

**Review by mattgarner — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1, 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_mosdepth/3)* status: all files reviewed, 3 unresolved discussions (waiting on @jethror1)

___
*[dxapp.json, line 6 at r5](https://reviewable.io/reviews/eastgenomics/eggd_mosdepth/3#-MCI5hsj6o-WAEioFYEE:-MCI5hskDVYcy8hj1GsI:b-7jhppg) ([raw file](https://github.com/eastgenomics/eggd_mosdepth/blob/65718819d4357545e0ef4ae1c1b43e95f7909201/dxapp.json#L6)):*
> ```JSON
>   "summary": "runs mosdepth to perform coverage analysis",
>   "dxapi": "1.0.0",
>   "version": "1.0.0",
> ```

Properties githubRelease
___
*[src/eggd_mosdepth.sh, line 17 at r5](https://reviewable.io/reviews/eastgenomics/eggd_mosdepth/3#-MCI6YExDmvjoSNC2eUx:-MCI6YEy4iFe3d7lOF0E:b-68i5mq) ([raw file](https://github.com/eastgenomics/eggd_mosdepth/blob/65718819d4357545e0ef4ae1c1b43e95f7909201/src/eggd_mosdepth.sh#L17)):*
<details><summary><i alt="summary">Quoted 8 lines of code…</i></summary>

> ```
>     if [[ $optional_arguments =~ "--by" ]]; then
>       # if bed file is being used
>       # DNAnexus doesn't seem to handle passing files through optional string well
>       # get full path of bed, then add the full bed path after --by to pass bed
>       bed_path=$(realpath ~/input/*.bed)
>       bed_arg="--by $bed_path"
>       optional_arguments="${optional_arguments/--by/$bed_arg}"
>     fi
> ```
</details>

What happens if you pass it --by but no bed file?
___
*[src/eggd_mosdepth.sh, line 55 at r5](https://reviewable.io/reviews/eastgenomics/eggd_mosdepth/3#-MCI6pKT0vBf0FgfP1dN:-MCI6pKT0vBf0FgfP1dO:b-v2pink) ([raw file](https://github.com/eastgenomics/eggd_mosdepth/blob/65718819d4357545e0ef4ae1c1b43e95f7909201/src/eggd_mosdepth.sh#L55)):*
> ```Shell
> 
>     # get conda and build it, required to install mosdepth
>     wget -q https://repo.anaconda.com/miniconda/Miniconda2-latest-Linux-x86_64.sh 
> ```

Include this file in the app to remove the external dependency

**Review by jethror1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_mosdepth/3)* status: 1 of 5 files reviewed, 3 unresolved discussions (waiting on @mattgarner)

___
*[dxapp.json, line 6 at r5](https://reviewable.io/reviews/eastgenomics/eggd_mosdepth/3#-MCI5hsj6o-WAEioFYEE:-MCLsbuuApQM8urvgLm8:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_mosdepth/blob/65718819d4357545e0ef4ae1c1b43e95f7909201/dxapp.json#L6)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Properties githubRelease
</blockquote></details>

Done.
___
*[src/eggd_mosdepth.sh, line 17 at r5](https://reviewable.io/reviews/eastgenomics/eggd_mosdepth/3#-MCI6YExDmvjoSNC2eUx:-MCLsu_-CcT3mkTEW-rH:b-z5xmox) ([raw file](https://github.com/eastgenomics/eggd_mosdepth/blob/65718819d4357545e0ef4ae1c1b43e95f7909201/src/eggd_mosdepth.sh#L17)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
>     if [[ $optional_arguments =~ "--by" ]]; then
>       # if bed file is being used
>       # DNAnexus doesn't seem to handle passing files through optional string well
>       # get full path of bed, then add the full bed path after --by to pass bed
>       bed_path=$(realpath ~/input/*.bed)
>       bed_arg="--by $bed_path"
>       optional_arguments="${optional_arguments/--by/$bed_arg}"
>     fi
> ```
What happens if you pass it --by but no bed file?
</blockquote></details>

Changed this to not need to pass the --by flag, just takes the bed file as input then the flag is added to the optional arguments at the beginning of the script
___
*[src/eggd_mosdepth.sh, line 55 at r5](https://reviewable.io/reviews/eastgenomics/eggd_mosdepth/3#-MCI6pKT0vBf0FgfP1dN:-MCLtA24ApPWwbzAPMXZ:b-jn7ivi) ([raw file](https://github.com/eastgenomics/eggd_mosdepth/blob/65718819d4357545e0ef4ae1c1b43e95f7909201/src/eggd_mosdepth.sh#L55)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Include this file in the app to remove the external dependency
</blockquote></details>

Added to resources dir

**Review by mattgarner — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r6.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_mosdepth/3)* status: 4 of 5 files reviewed, 5 unresolved discussions (waiting on @jethror1 and @mattgarner)

___
*[dxapp.json, line 7 at r6](https://reviewable.io/reviews/eastgenomics/eggd_mosdepth/3#-ME75jMCDwk4q76l3ch-:-ME75jMCDwk4q76l3ch0:bu5nuyx) ([raw file](https://github.com/eastgenomics/eggd_mosdepth/blob/2c3fa08872ae53e9c8c6801c008d10f33c40911e/dxapp.json#L7)):*
> ```JSON
>   "dxapi": "1.0.0",
>   "properties": {
>   "github release": "v1.0.0"
> ```

Almost. Should be camelBack to be consistent with the rest of the file.
"githubRelease":
___
*[src/eggd_mosdepth.sh, line 68 at r6](https://reviewable.io/reviews/eastgenomics/eggd_mosdepth/3#-ME77Y-41ccTgI6ennRe:-ME77Y-41ccTgI6ennRf:bx98avj) ([raw file](https://github.com/eastgenomics/eggd_mosdepth/blob/2c3fa08872ae53e9c8c6801c008d10f33c40911e/src/eggd_mosdepth.sh#L68)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>     # add required channels for mosdepth
>     conda config --add channels bioconda
>     conda config --add channels conda-forge
>     conda install mosdepth
> ```
</details>


Can we eliminate these external dependencies?

**Review by jethror1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_mosdepth/3)* status: 4 of 5 files reviewed, 5 unresolved discussions (waiting on @mattgarner)

___
*[dxapp.json, line 7 at r6](https://reviewable.io/reviews/eastgenomics/eggd_mosdepth/3#-ME75jMCDwk4q76l3ch-:-MF60S_hDQsyTzUiXAeq:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_mosdepth/blob/2c3fa08872ae53e9c8c6801c008d10f33c40911e/dxapp.json#L7)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Almost. Should be camelBack to be consistent with the rest of the file.
"githubRelease":
</blockquote></details>

Done.
___
*[src/eggd_mosdepth.sh, line 17 at r5](https://reviewable.io/reviews/eastgenomics/eggd_mosdepth/3#-MCI6YExDmvjoSNC2eUx:-MCLu3Zj3KMOQaDCxuMy:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_mosdepth/blob/65718819d4357545e0ef4ae1c1b43e95f7909201/src/eggd_mosdepth.sh#L17)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

Changed this to not need to pass the --by flag, just takes the bed file as input then the flag is added to the optional arguments at the beginning of the script
</blockquote></details>

Done.
___
*[src/eggd_mosdepth.sh, line 68 at r6](https://reviewable.io/reviews/eastgenomics/eggd_mosdepth/3#-ME77Y-41ccTgI6ennRe:-MF60Voq15f-AmnrZkkw:bxbiwvn) ([raw file](https://github.com/eastgenomics/eggd_mosdepth/blob/2c3fa08872ae53e9c8c6801c008d10f33c40911e/src/eggd_mosdepth.sh#L68)):*
> external
Changed to use local docker image, now has no external dependencies

**Review by mattgarner — APPROVED** [review]
> Reviewed 1 of 5 files at r7, 1 of 3 files at r9, 3 of 3 files at r11.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_mosdepth/3)* status: all files reviewed, 3 unresolved discussions (waiting on @mattgarner)

**Pull request merged**
